### ISSUE TITLE
Makefile for Linux

### ISSUE THREAD

**Issue by lieux** [poolpOrg/fion#1]
I would like to try out `fion` on Linux. Will this be possible?

**Comment by poolpOrg** [comment]
It will take a while before it is usable but code should be portable so I'll make it build on Linux soon.

**Comment by lieux** [comment]
Great news. Thanks! :D

**Comment by poolpOrg** [comment]
Makefile has been adapted to allow building on Linux and MacOS.

I'm now using an Ubuntu CI on this repo, confirming that it builds on Linux
